### ISSUE TITLE
builder loading issues

### ISSUE THREAD

**Issue by kingkoz1313** [Maetrim/DDOBuilderV2#1]
Hello, I just downloaded your latest v2 beta of the DDO Builder. After unzipping, I clicked the .exe and the program started up. But sat for about 2 minutes showing "not responding" then the builder finally responded and I got a bunch of errors in the log window. Not sure how to cut/paste a line but they are saying that the .png files in the Classimages directory are the wrong size.looks like ALL the files in that directory are erroring. The program stops responding when it gets to "loading Enhancement trees...99. Then it loads the rest and then errors with the images in classimages directory. 

I am running DDO on a Windows 10 v21h2 with an AMD FX(tm)-8320 Eight-Core Processor  @4.00 GHz with 16gigs ram and a ATI Rx500x video card. If you have any questions, feel free to email me.

John

**Comment by Maetrim** [comment]
The builder can currently appear to hang at the point of loading the items, this can take a long time as there are around 7k items at present. I will be decoupling the item loading from the interface at some point so this will become less of an issue.

There is an option in the edit menu to copy the log content to the clipboard. (its how I track my errors in the items etc)

Not sure about the images being the incorrect size. If you didn't extract to the same location as V1 of the builder they should be completely separate.

**Comment by kingkoz1313** [comment]
Thanks for the reply. The builder does "appear to hang" (as you say) for about 3minutes. Then it continues until it hits the errors loading images. Unfortunately I do not see and option to copy the log. It is at the bottom of the builder window and will only let me copy 1 line. There are several error lines. Can you please direct me to the menu option that will allow me to send the logs to you? I do not see anywhere (other than the log file at the bottom of the builder) to copy the logs.
 
 
-----Original Message-----

**Comment by Maetrim** [comment]
There should be an option in the Edit menu to copy the log to the clipboard.

At this point, there is no need to report the log to me as I check the content after almost every build.

I am more interested in bugs outside of the obvious that are reported in the UI at the moment.

**Comment by Maetrim** [comment]
Closed as was for a very old version.
