### ISSUE TITLE
FvS Battle Feat not appearing

### ISSUE THREAD

**Issue by MuazAlhaidar** [Maetrim/DDOBuilderV2#10]
![image](https://github.com/Maetrim/DDOBuilderV2/assets/24642260/b77ab19c-b214-4037-b7bc-9758ebef5068)

**Comment by MuazAlhaidar** [comment]
![image](https://github.com/Maetrim/DDOBuilderV2/assets/24642260/2779d75b-166a-4017-89bd-a3a62ea7f725)
Heart feat isnt appearing either

**Comment by Maetrim** [comment]
This has been fixed for the next release.
