### ISSUE TITLE
Fury of the Wild's Sprit of the Beast not affecting Ram's Might

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#100]
Ram's Might's effects should be doubled by Spirit of the Beast (T3 Fury of the Wild).

So it should provide a +4 size bonus to strength and a +4 size bonus to damage. 

Ram's Might only provides the normal +2 to both even with Spirit of the Beast active.

I'm assuming this also is true for Animal Growth, which should also be doubled by this same destiny ability, but I've not personally tested it yet.

**Comment by Maetrim** [comment]
Fixed for next release, for both spells.
