### ISSUE TITLE
Ring of Unbridled Might's insightful accuracy incorrectly stacks with Dragonlord's strength trance.

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#101]
I haven't had time to isolate what the exact bug is here. I'm not sure if Dragonlord's strength trance is stacking with all other sources of insightful accuracy or if it's specific to this item. I'm also not sure if it happens with Dragonlord's charisma trance.

**Comment by Maetrim** [comment]
Fixed for Dragon Lord stances and all other Battle Trances effects (it was a 50% chance they were correct already)
