### ISSUE TITLE
Druid spell list missing spells

### ISSUE THREAD

**Issue by Rehmlah** [Maetrim/DDOBuilderV2#108]
The (base, non-archetype) druid spell list is missing the thorn spells, spells converted from old Epic Destinies, and a few others. Specifically:
1: Merfolk's Blessing, Thorn Strike
3: Thorn Bloom
5: Thorn Wave
6: Grasping Thorns
7: Insidious Spores
8: Stormrage, Thorn Lance
9: Tsunami

**Comment by Maetrim** [comment]
All added to the Druid spell list
