### ISSUE TITLE
universal artifact crit chance bug

### ISSUE THREAD

**Issue by christhemisss** [Maetrim/DDOBuilderV2#112]
artifact universal crit chance (such as elders) does not stack with typed artifact spell crit chance (such as sharn sets)

**Comment by Maetrim** [comment]
I have been getting conflicting reports about this for the Elder's Knowledge Artifact bonus to spell critical. I have been told it stacks and now I am being told it doesn't stack. I have posted a comment about this in the V2 forum post looking for clarification.

**Comment by Mummykiller** [comment]
it stacks i was using it last life having a specific crit chance to lets say cold and then a crit chance to all things on the sets gives u both of them to crit chance for a total lf 12%

**Comment by Mummykiller** [comment]
i cant prove it right now since i tr'ed but if u want when i get to 32 ill send a few pics

**Comment by Maetrim** [comment]
This should have been fixed in the last build.
