### ISSUE TITLE
Warforged weapon attachment blocks the wrong thing 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#116]
![image](https://github.com/user-attachments/assets/a24a8743-97df-4835-951a-f617a4337faa)
![image](https://github.com/user-attachments/assets/ac225e43-92ff-4bc9-9c40-ba0c7c41a5ef)
Should only block the Battle engineer:weapon attachment

**Comment by Maetrim** [comment]
Fixed for next release.
