### ISSUE TITLE
Vistani core blocked by having deflect arrows 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#120]
![image](https://github.com/user-attachments/assets/ad6a1aa5-46ea-4885-a62e-dee52fe9f839)
![image](https://github.com/user-attachments/assets/ab566c1b-fd6b-4107-a8a5-fff98a18685e)

**Comment by Maetrim** [comment]
Exclusion group now only applies to Swashbuckler/Tempest and Sacred Fist trees as mentioned in the Wiki.
