### ISSUE TITLE
Swashbuckling doesn't apply the correct competence bonuses to threat range and multiplier for some weapons

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#121]
It may just be the first group, short sword, dagger, and throwing daggers, but I'm not sure if there are others that are incorrect. I think rapier was getting +2 multiplier instead of +1 as well.

**Comment by Maetrim** [comment]
I reviewed and reworked all the Swashbuckling enhancements for improved critical and Swashbuckling interaction and fixed various issues.
