### ISSUE TITLE
Shillelagh bonus weapon dice not applying to special wood types

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#122]
I believe that Shillelagh still works on the "special" types of wood in addition to weapons that are just "wooden". I haven't had a chance to test this personally yet, but that's my understanding.

So that would mean Darkwood and Densewood, I'm not sure if there are any others.

Example densewood quarterstaves are the Legendary Broken Oar (crystal cove) and Legendary Moonbeam. I'm not sure if there are any darkwood staves but if there were I think it would still apply.

**Comment by Maetrim** [comment]
Fixed for Densewood and Darkwood items (if there are any)
