### ISSUE TITLE
arti bugs

### ISSUE THREAD

**Issue by christhemisss** [Maetrim/DDOBuilderV2#127]
ability engine and unlock potential dont work even with a rune arm equipped (tovens hammer in my case)

**Comment by Maetrim** [comment]
Was this in build 37? I fix in this areas was applied in the last version released.

**Comment by Maetrim** [comment]
I just tested in my local build. An arti using Legendary Tovens Hammer, and taking Agaility Engine and Unlock potential both appear to work.
![image](https://github.com/user-attachments/assets/0cc47a1c-82b8-4a21-b023-b2c84a650e16)

**Comment by christhemisss** [comment]
ill send my build file tomorrow, maybe i did something wrong

**Comment by Maetrim** [comment]
Please open a new issue if you see this again.
