### ISSUE TITLE
emerald of arcane empowerment bug

### ISSUE THREAD

**Issue by christhemisss** [Maetrim/DDOBuilderV2#128]
it does not stack with greater elemental weapons

**Comment by Maetrim** [comment]
Do we know what bonus type the "Greater Elemental Weapons" spell types its +2 Imbue Dice as?
The wiki doesn't specify directly, so I just picked the most obvious, should the type be "Temporary"?

**Comment by christhemisss** [comment]
it stacks with everything except itself afaik

**Comment by christhemisss** [comment]
its an alchemical bonus

**Comment by Maetrim** [comment]
I'll set it to alchemical for all spells which grant bonus imbue dice.
