### ISSUE TITLE
"Epic Spell Power:Sonic" is missing from the Destiny feats list.

### ISSUE THREAD

**Issue by NightHikerTM** [Maetrim/DDOBuilderV2#131]
Heyas!

As described in the title.

Cheers!

**Comment by RogerIanAllen** [comment]
A bad install setup created a while back includes that feat in the Ignore list. There should be an file call something like "IgnoreList.xml" in your installation folder (or the DataFiles folder). That file can be safely deleted and the feat should re-appear again.

**Comment by NightHikerTM** [comment]
Gotcha. Thaks for the reply!
