### ISSUE TITLE
Feature Request : Add an url list to get item, instead of crawling all the wiki

### ISSUE THREAD

**Issue by ydufraisse** [Maetrim/DDOBuilderV2#132]
Well as the title say, update 69 items seems to be missing, and it's not a good thing if everyone is going to crawl all the wiki just to get the update 69 items.
So if we could just add an url like "https://ddowiki.com/page/Category:Update_69_named_items" and it could crawl only this update, that would be nice.

**Comment by Maetrim** [comment]
Feature added (and being used by me :D). Available to users in the next release.
