### ISSUE TITLE
Elemental forms and sky/sea attunement

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#140]
![image](https://github.com/user-attachments/assets/9ef0a23d-1cbf-4597-b866-629b445450ac)
![image](https://github.com/user-attachments/assets/1a11e0e6-3bae-4532-9f13-3218fe59bcea)
![image](https://github.com/user-attachments/assets/91712e2f-91b7-49af-90e3-61dfcc6a12af)
![image](https://github.com/user-attachments/assets/21377ea5-e61d-4b66-92ca-dd9946966a58)

**Comment by Mummykiller** [comment]
it should give 2% crit chance

**Comment by Mummykiller** [comment]
i tried it on druid and on sorc both dont work

**Comment by Maetrim** [comment]
Effects added for the Fire/Water Elemental forms for Sea/Sky Attunement
