### ISSUE TITLE
Missing quality deception from mythic rings 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#145]
![image](https://github.com/user-attachments/assets/645a68a4-84cb-4103-aafd-780f6e53c974)
![image](https://github.com/user-attachments/assets/63c972e5-4e2e-43f5-94a6-01325482c65f)

**Comment by Mummykiller** [comment]
from all the rings that are from the slayer area 
there are 6 of them (one for each stat) and all of them are the same xd

**Comment by Maetrim** [comment]
All 6 items fixed
