### ISSUE TITLE
New minor artifact 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#146]
![image](https://github.com/user-attachments/assets/8b349e1d-107e-4be4-a4fb-1f514ab7cb07)
![image](https://github.com/user-attachments/assets/53bfc9b9-c7e8-40be-b598-2472e29a035d)

**Comment by Mummykiller** [comment]
improved deception instead of deception

**Comment by Maetrim** [comment]
Fixed for next release.
