### ISSUE TITLE
File conversion from V1

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#15]
This is only an 'issue' if one doesn't exist, but I've failed to find one.  
At a minimum, V2 won't natively find V1 files (.ddocp vs .DDOBuild).
Using '*.*' for the file open dialog and trying to simply open a V1 file in V2 generates an XML error (unsurprising), which suggests the file format has changed.
And I can neither find an export function in V1 (except for forum export), nor a conversion in V2.

So, is there a file conversion available for existing V1 builds?  Or must they be manually re-entered in V2?  If there's no conversion, will there be?  If not, why not?

You know.. stuff like that.

**Comment by Maetrim** [comment]
No file migration at the moment, its something for me to work on in the future.

**Comment by Maetrim** [comment]
This feature has now been added.
