### ISSUE TITLE
Arcane actions (new epic destiny feat)

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#152]
imbue doesnt work
![image](https://github.com/user-attachments/assets/1e239138-618c-46c8-8051-cd18008bbbed)

should give 50 not 50%
![image](https://github.com/user-attachments/assets/9b463678-4c4c-45ba-af09-36a2f56ddfe3)

**Comment by Maetrim** [comment]
Accidentally had the <Percent/> flag set on the item. Fixed.
