### ISSUE TITLE
Vulkoor's might 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#153]
![image](https://github.com/user-attachments/assets/f29f51f3-d6f5-4420-8fcd-e7ec4fbac1d3)
![image](https://github.com/user-attachments/assets/71d2f130-cc1b-4b75-814f-608680abc659)

**Comment by Mummykiller** [comment]
missing +3 artifact bonus to seeker

**Comment by Mummykiller** [comment]
and threat gen global not melee only

**Comment by Maetrim** [comment]
Fixed for next release (Also fixed Epic/heroic where required)
