### ISSUE TITLE
Paladin shouldnt be able to take magical training at level 1

### ISSUE THREAD

**Issue by MuazAlhaidar** [Maetrim/DDOBuilderV2#154]
![image](https://github.com/user-attachments/assets/d52ba4dd-052e-492b-819d-d65daa8884c8)
Paladin shouldn't be able to take magical training feat until level 4 when they can cast their first level 1 spell.
https://ddowiki.com/page/Magical_Training
**Prerequisite:** Ability to cast level 1 Spells.

**Comment by Maetrim** [comment]
Fixed for next release. Also fixed for Ranger (level 4) and Bard (Selectable level 1)
