### ISSUE TITLE
Lesser Displacement Bug

### ISSUE THREAD

**Issue by Ozmandias42** [Maetrim/DDOBuilderV2#157]
While Blurry items are providing an Enhancement bonus to Concealment and correctly non-stacking with the Blur spell, Lesser Displacement items are displaying an Equipment bonus and incorrectly stacking with the Blur spell.
![image](https://github.com/user-attachments/assets/30c32785-b9cd-4b57-b0dd-1700ee222d36)

**Comment by Maetrim** [comment]
Fixed for next release.
