### ISSUE TITLE
Shield % Bonus Bug

### ISSUE THREAD

**Issue by Ozmandias42** [Maetrim/DDOBuilderV2#158]
When I add points into the Shield Prowess enhancement in the Unyielding Sentinel Epic Destiny, the Shield % Bonus stat increases, but my overall AC does not increase. There is also no "Shield % Bonus" line present in my AC breakdown list.
![image](https://github.com/user-attachments/assets/1217919d-5084-4f2c-ae8b-b1afd6de0a92)

![image](https://github.com/user-attachments/assets/efdb175e-4fb7-4f92-8835-842877cbdae4)

**Comment by Maetrim** [comment]
Are you actually using a shield?

**Comment by Maetrim** [comment]
ok. With some further investigation some schenanigans is going on...

**Comment by Maetrim** [comment]
Fixed for next release.
