### ISSUE TITLE
Filigree Slotting Issue

### ISSUE THREAD

**Issue by nadia72295** [Maetrim/DDOBuilderV2#163]
When clicking on a filigree slot, not filling the slot, and then clicking on another filigree slot, the program will fill the previously clicked empty filigree slots with the filigree inserted into the last slot clicked. This can be done with any number of previously clicked filigree slots as long as you don't click anywhere other than the 'Gear and Filigrees' tab.

1. Click on a Filigree Slot (slot 10 pictured)
![FiligreeSlotIssue_SlotTenSelect](https://github.com/user-attachments/assets/2e5d40a5-1104-4a9e-9948-fd54196926cb)

2. Without selecting a filigree for the first Slot, click on a second Slot (slot 1 pictured)
![FiligreeSlotIssue_SlotOneSelect](https://github.com/user-attachments/assets/d8521162-d457-4a3d-8d3a-9c9793667a3d)

3. Fill the second Slot. Both slots will have the same Filigree slotted in them.
![FiligreeSlotIssue_BothSlotsFilled](https://github.com/user-attachments/assets/a5029ace-61fe-43cc-b0ce-a272be4ad9ff)

Bonus: Insert "500 Cigarettes" Meme, 30 extra imbue dice
This was just clicking all the Slots from 30 to 1, only putting the Imbue Die filigree into Slot 1.
![FiligreeSlotIssue_FiveHundredFiligrees](https://github.com/user-attachments/assets/97810ffb-5997-4f27-9a41-98c5efa93123)

**Comment by Maetrim** [comment]
Fixed for next release.
