### ISSUE TITLE
mutli element spell power effects 

### ISSUE THREAD

**Issue by Daawsomeone** [Maetrim/DDOBuilderV2#164]
Items with nullification bonuses are not giving poison spell power

items with radiance bonuses are not giving evil or chaos spell power. Radiance Lore items also are not giving evil or chaos crit chance. 

items with reconstruction bonuses are not giving rust spell power, Reconstruction Lore items also are not giving rust crit chance 

items with impulse bonuses are not giving physical spell power

if unintended ( unclear as they all only list the one element and I can't confirm any in game) the crit damage dinosaur bone accessory effects for light, repair, and force do not give their respective other elements tied to the main spell power/lore bonuses

**Comment by Maetrim** [comment]
I reviewed all Spell Power / Lore / Multipliers for all these types and did modifications as required (lots of changes).

Its worth checking some things to see if I got them right in the next release.
