### ISSUE TITLE
Can't add Legendary Five Rings item to trinket slot

### ISSUE THREAD

**Issue by mccoole** [Maetrim/DDOBuilderV2#166]
When I click on the trinket slot the available items do not include the Legendary Five Rings slaver's item which can go in the trinket slot and I can't change the item type that it filters on.  Legendary Five Rings do show up for the ring slots though.

**Comment by SpartanKiller13** [comment]
Shackles also don't have an option to go to boots.
Was fixed in .31, but probably got broken since
Slave lords dual-slot stuff is a pain XD

**Comment by Maetrim** [comment]
Fixed for next release. I also update dthe parser to stop this happening in the future.

**Comment by mccoole** [comment]
Thanks for such a quick turn around. Love the builder!Sent from my iPhone. Auto correct typos likely.On Sep 29, 2024, at 3:00 PM, Maetrim ***@***.***> wrote:﻿
Fixed for next release. I also update dthe parser to stop this happening in the future.
