### ISSUE TITLE
Bard and Barbarian Alignment Issue

### ISSUE THREAD

**Issue by nadia72295** [Maetrim/DDOBuilderV2#168]
Bard and Barbarian are locked out when the Neutral Good alignment is selected when both are "Any Non-Lawful" classes. All other valid alignments for these two classes are working as they should.
![AlignmentIssueNG](https://github.com/user-attachments/assets/6db0ca42-da49-43c4-91d4-71308fedfb63)

**Comment by Maetrim** [comment]
Fixed for next release (also Stormsinger)
