### ISSUE TITLE
Missing Dino Bone Orb Bonus Issue

### ISSUE THREAD

**Issue by nadia72295** [Maetrim/DDOBuilderV2#169]
The Dinosaur Bone Orb is missing its +15 Orb Bonus
In the Builder:
![DinoOrbBuilder](https://github.com/user-attachments/assets/c4da3168-414c-4fa6-8f1f-39d893130421)
In the Game:
![DinoOrbInGame](https://github.com/user-attachments/assets/c88ffa9a-b6a9-468a-adb1-cedcb87f4694)

**Comment by Maetrim** [comment]
Fixed for next release.
