### ISSUE TITLE
Standard Feats not showing on list when taking an epic feat

### ISSUE THREAD

**Issue by Melkizadek1** [Maetrim/DDOBuilderV2#17]
I know you can get around this by showing all feats even if you are not eligible. Is there a way to have the standard feats that you are eligible for populate in the list without having to show all feats?

**Comment by Melkizadek1** [comment]
It does not look like you can select standard feats in an epic feat slot even with the toggle is turned on, so maybe the standard feats just need to be flagged as eligible in epic feat slots?

**Comment by Maetrim** [comment]
![image](https://github.com/Maetrim/DDOBuilderV2/assets/30188223/1edfa787-5a8a-4b9a-bb07-f3693092c4b7)
You need to disable the "Epic feats only" for epic feats slots to get them to show up.
