### ISSUE TITLE
Weapon/Shield Search Issue

### ISSUE THREAD

**Issue by nadia72295** [Maetrim/DDOBuilderV2#171]
I have noted a couple of issues with the Weapon/Shield Search in the latest update (verified with a completely fresh install, though this could still just be something funky with my machine?)

1. Dinosaur/Attuned Bone Weapons are not visible in their respective Item Type categories, but visible on the All type
![MissingAttunedBoneLongsword](https://github.com/user-attachments/assets/058afe53-bbc2-489c-adaa-c517a63e2638)
![AllDinosaurBone](https://github.com/user-attachments/assets/9e694a36-f49b-4549-b2ea-de9351285351)

2. Moving from a freshly opened All type Search Box to any specific Item Type makes the All type completely blank unless the search window is closed and reopened. You can switch between different specific Item Types without issue.(In the images, I just used the scroll wheel to scroll down to Bastard Swords and then back up to All, but it works when manually selecting an Item Type from the dropdown as well.)
![WeaponSearchMain](https://github.com/user-attachments/assets/62b45c4e-0f00-4028-8807-5c65aa1da702)
![WeaponSearchBSword](https://github.com/user-attachments/assets/ee14a0b4-442d-45be-8eb6-368cf397cb73)
![WeaponSearchMainScroll](https://github.com/user-attachments/assets/0c596328-8884-4221-9daa-527a531f9f81)

**Comment by Maetrim** [comment]
A problem with all craftable weapons was fixed.
