### ISSUE TITLE
I am a fucking idiot

### ISSUE THREAD

**Issue by MuazAlhaidar** [Maetrim/DDOBuilderV2#172]
Previous Issue related to this:
https://github.com/Maetrim/DDOBuilderV2/issues/154

Anyone can take the magical training feat at any level.
The wiki was wrong and I double checked in game that you can as a fighter take magical training at level 1.

https://ddowiki.com/page/Magical_Training
The wiki page has now been updated.

**Comment by Maetrim** [comment]
Fixed for next release.
