### ISSUE TITLE
Incremented Abilities need to be isolated per build

### ISSUE THREAD

**Issue by MrEkshin** [Maetrim/DDOBuilderV2#175]
Build 1 increments Wisdom. This sets Wisdom as used for build 2. 
Yet Build 2 is then set to increment Constitution. Which then retroactively messes up the incremented abilities on build 1.
Please make the incremented Abilities separate per build.
![attributePer4Level-2](https://github.com/user-attachments/assets/94cab791-c352-4c9d-906f-104ada97f381)

**Comment by Maetrim** [comment]
Broken out to the build level. For older loaded files all builds within a given life get the Life's current values, which are then cleared.

**Comment by MrEkshin** [comment]
Forgive me, but I don't understand your response. Does this mean that every time I switch between builds, the values keep changing? My ability scores are separate per build within a life. Why would the incremental modifiers be?
