### ISSUE TITLE
Listed SLA's should be isolated per build.

### ISSUE THREAD

**Issue by MrEkshin** [Maetrim/DDOBuilderV2#176]
Build 1 uses the Sunbolt SLA.
DDOBuilder then includes those SLAs in the listing for build 2, even though build 2 doesn't use the Sunbolt SLA.
Please display SLAs only for their respective builds.
![SLA_Isolation-2](https://github.com/user-attachments/assets/d54f5d28-e67b-4dd8-a2f5-6a380cf68ece)

**Comment by Maetrim** [comment]
Also fixed for next release.
