### ISSUE TITLE
Draconic Incarnation "Gaping Maw" Typo

### ISSUE THREAD

**Issue by MrEkshin** [Maetrim/DDOBuilderV2#180]
Text reads,
 "Your Dragon Breath Epic Strike now deals d1d6+10 damage per Caster Level."

Should remove leading extra "d" in dice formula, to read,
 "Your Dragon Breath Epic Strike now deals 1d6+10 damage per Caster Level."
![Gaping_Maw-1](https://github.com/user-attachments/assets/b34c3b12-dffb-4dec-8d68-88eae1b98f8c)

**Comment by Maetrim** [comment]
Fixed for next release.
