### ISSUE TITLE
Occult Slayer Bond of Retribution and Destruction

### ISSUE THREAD

**Issue by trucnar** [Maetrim/DDOBuilderV2#181]
Bond of Retribution applies correctly (at 50% HP) but is listed under Critical Multiplier instead of Critical Multiplier (19-20).
Bond of Destruction does not show up in the breakdown or remove the HP requirement.

![image](https://github.com/user-attachments/assets/aa5f1618-e7c2-4ac9-960f-594a19ed07b1)

**Comment by Maetrim** [comment]
Fixed for next release.
