### ISSUE TITLE
Artificer: Arcanotechnician tree, "Energy of the Creator" incorrect title.

### ISSUE THREAD

**Issue by MrEkshin** [Maetrim/DDOBuilderV2#186]
Builder:
The Title reads "Energy of Creation"
![EnergyOfTheCreator-2](https://github.com/user-attachments/assets/f5443a55-924f-4e43-bec0-398973b0d366)

In game:
The title should read, "Energy of the Creator"
![EnergyOfTheCreator-1](https://github.com/user-attachments/assets/152f6b37-a565-4b56-a391-3029e20e1532)

**Comment by Maetrim** [comment]
Fixed for next release.
