### ISSUE TITLE
Vistani Mist Stalker 1 (Tier 1 Vistani Ability) Not able to be selected with 2 points left to spend.

### ISSUE THREAD

**Issue by Melkizadek1** [Maetrim/DDOBuilderV2#19]
It is acting a little odd.  When I have 3 points left to spend (2 universal and 1 standard) it lets me purchase it, but if I only have 2 points left to spend, I cannot purchase it unless I have put 2 points into the tree already. Maybe it is not playing nicely with Universal Action Points?

**Comment by Maetrim** [comment]
This is a weird one, spent some time on it, but not got a red flag yet

**Comment by Maetrim** [comment]
Found and fixed for next release
