### ISSUE TITLE
Divine Disciple Minor Bugs

### ISSUE THREAD

**Issue by Ozmandias42** [Maetrim/DDOBuilderV2#191]
Divine Disciple Core 2 Empowered by Light is giving 3 MRR, but the Wiki indicates it gives 3 PRR

Divine Disciple Core 4 selector is requiring Cleric 12, even though one of the options only requires Cleric 6

**Comment by Ozmandias42** [comment]
Also Divine Disciple Core 6 Priest of Endless Light and Divine Disciple Tier 5 Acceptance do not appear to change my caster level and max caster level in the spell descriptions

**Comment by Maetrim** [comment]
Fixed the PRR issue in core 2. Core 4 appears correct, the different "Cleric" levels at each is because the light enhancements go left to right at levels 1,3,6,12,18,20 and the dark enhancements got right to left as 20,18,12,6,3,1, this means that core one is 1/20, core 2 3/18, core 3, 6/12, core 4 12/6, core 5 18/3 and core 6 20/1.

The caster level stuff is a bit more difficult to fix, but should be doable. The spell list affected appears to be:

            <Item>Divine Punishment</Item>
            <Item>Divine Wrath</Item>
            <Item>Nimbus of Light</Item>
            <Item>Searing Light</Item>
            <Item>Sun Bolt</Item>
            <Item>Sunbeam</Item>
            <Item>Sunburst</Item>
            <Item>Deific Vengeance</Item>
            <Item>Contagion</Item>
            <Item>Unholy Blight</Item>
            <Item>Order's Wrath</Item>
            <Item>Chaos Bolt</Item>
            <Item>Chaos Sphere</Item>
            <Item>Chaos Hammer</Item>
            <Item>Wildstrike</Item>

Negative spells are:

            <Item>Chill Touch</Item>
            <Item>Energy Drain</Item>
            <Item>Enervation</Item>
            <Item>Finger of Death</Item>
            <Item>Ghoul Touch</Item>
            <Item>Harm</Item>
            <Item>Inflict Light Wounds</Item>
            <Item>Inflict Critical Wounds</Item>
            <Item>Inflict Moderate Wounds</Item>
            <Item>Inflict Serious Wounds</Item>
            <Item>Ray of Enfeeblement</Item>
            <Item>Ray of Exhaustion</Item>
            <Item>Slay Living</Item>
            <Item>Symbol of Death</Item>
            <Item>Symbol of Weakness</Item>
            <Item>Wail of the Banshee</Item>
            <Item>Waves of Exhaustion</Item>
            <Item>Waves of Fatigue</Item>
            <Item>Necrotic Bolt</Item>
            <Item>Negative Energy Burst</Item>
            <Item>Necrotic Ray</Item>
            <Item>Necrotic Blast</Item>
            <Item>Improved Harm</Item>
            <Item>Rend the Soul</Item>
