### ISSUE TITLE
Dragon Lord Ravager Cruel Cut Rank 3 Text Missing

### ISSUE THREAD

**Issue by trucnar** [Maetrim/DDOBuilderV2#192]
Builder v2.0.0.47
The DL Ravager Cruel Cut ability tree has rank 3 extra text which is missing.

Dragon Lord Ravager T2 Cruel Cut text missing "Rank 3 of Cruel Cut now adds +1d6 of additional Constitution Damage for every 2 Character Levels you have."

Dragon Lord Ravager T3 Festering Wound text missing "Rank 3: Festering Wound becomes Greater Festering Wound and gains an additional 1d6 Poison Damage for every 10 Character Levels you have. Also affects bosses."

Dragon Lord Ravager T4 Dismember text missing "Rank 3: Your Slashing Damage from Dismember increases by +1d8 for every 2 Character Levels you have. (Movement and attack speed debuffs last for 5 seconds each and affect bosses.)"

**Comment by Maetrim** [comment]
Reviewed the entire tree and fixed all errors spotted.
