### ISSUE TITLE
Metamagic Cost Reduction 'inactive'

### ISSUE THREAD

**Issue by trucnar** [Maetrim/DDOBuilderV2#193]
Builder v2.0.0.47
Metamagic cost reduction from enhancements or items appear inactive.
Toggled metamagic on/off to no effect.
I selected feats first then enhancements/items, haven't tested alternate methodologies.

Archmage Enhancement
![Enhancement Efficient Metamagic](https://github.com/user-attachments/assets/1d36adcd-be49-4f64-9d43-fe516fd79f3f)

Item Metamagic Efficiency
![Item Efficient Metamagic](https://github.com/user-attachments/assets/58f7eaaf-cae3-4e2d-b04a-7d890a574459)

**Comment by Maetrim** [comment]
Erroneous requirements in all metamagic effects across many many tree fixed.
