### ISSUE TITLE
Spell Cost Reduction Percent breakdown does not appear to be implemented

### ISSUE THREAD

**Issue by trucnar** [Maetrim/DDOBuilderV2#194]
Builder v2.0.0.47
Spell cost reduction from EDs or items do not show up under the Spell Cost Reduction Percent breakdown.

Tested with Draconic Incarnation cores, Fatesinger T3 Masquerade destinies and with Legendary Pendant of the Azure Sea item.

![Spell Cost Reduction](https://github.com/user-attachments/assets/ff224448-bad9-4155-b5d4-05459f25830d)

This tool is amazing!
Thank you and keep up the great work.

**Comment by Maetrim** [comment]
Missing effects added in required places.
