### ISSUE TITLE
Notes section doesn't scroll

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#195]
I'm adding past lives of my main toon to the V2 planner and I copied and pasted my notes on a couple of builds into the Notes pane and, as noted, no scroll bar appears if the notes are longer than the window, nor does scrolling appear to function.

If I click in the window and up-arrow to the top, nothing happens either.  I have no idea if all the text is in there and just not visible/accessible, or if the beginning was simply discarded.

**Comment by Maetrim** [comment]
Fixed for next release.
