### ISSUE TITLE
Re-issue/rewrite:  Reformat the build description so the Epic and Legendary levels are separated from the Heroic ones

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#197]
The current layout interleaves the Epic and Legendary level info among the Heroic levels in the cases of multiclasses, making it difficult to parse the multiclass levels.

In the Main pane, the one where one sets Name, Race, Alignment, initial Attributes, Tomes, etc., a better format would be to use two lines: one for the Heroic level breakdown of classes, and one beneath it for the Epic and Legendary levels (when they exist).

In the Builds pane, the Race is missing from the Life info.  So ideally it would have two lines as well:
First with the current "Build #: Level ## - " but followed by the Race
Second with Heroic classes, THEN Epic levels, and only finally Legendary levels.

This would make parsing the build info much clearer both in the Builds pane and the Main pane.

**Comment by Maetrim** [comment]
I updated the class data to look like this: 20 Paladin, E10, L4 (pure) or
<x> Class1, [y] Class2, [z] Class3, En, Ln   (E and L fields not present if no Epic or legendary levels)
I also added the race to the builds pane
