### ISSUE TITLE
Spells Missing from Ranger Spell List

### ISSUE THREAD

**Issue by MuazAlhaidar** [Maetrim/DDOBuilderV2#199]
![image](https://github.com/user-attachments/assets/768d220d-5bfa-4b44-83e6-5c517e7ee521)
Jump missing from level 1 spells

![image](https://github.com/user-attachments/assets/85bf1df2-ff9a-4c3e-8921-d68fcefdcf8d)
Cure Moderate Wounds missing from level 3 spells

![image](https://github.com/user-attachments/assets/0786008a-edb7-4a7b-8b07-e60b5b317185)
Freedom of Movement missing from level 4 spells
Cure Serious Wounds Mass is supposed to be regular Cure Serious Wounds

https://ddowiki.com/page/Ranger_spells

**Comment by Maetrim** [comment]
Can you check you have not accidentally added these spells to your "Ignore List". This happens during combo selection with a right click event. With ignored items shown you can recover these into the list with another right click.

![image](https://github.com/user-attachments/assets/14ab343b-a218-408b-93ac-47f3273277ce)
The item shown in the toolbar above needs to be selected.

**Comment by MuazAlhaidar** [comment]
Heyo I have tried it with the ignore list on
![image](https://github.com/user-attachments/assets/c69f27e0-45c6-484a-b01f-31441c44ee1e)
![image](https://github.com/user-attachments/assets/7d1b1291-1fe2-449d-b5ae-e5fb58ac1063)
![image](https://github.com/user-attachments/assets/25f7276c-43c5-42ab-9037-2ded478b399e)

this is builder version 2.0.0.47

**Comment by MuazAlhaidar** [comment]
![image](https://github.com/user-attachments/assets/f9c14bcf-a238-46ed-8135-10dac6e7dab1)

**Comment by MuazAlhaidar** [comment]
[Horse_Racial_09_DrowBowmans.zip](https://github.com/user-attachments/files/17987392/Horse_Racial_09_DrowBowmans.zip)
Attached is my ddo build file for my build if you wanna open it on your end

**Comment by Maetrim** [comment]
Issue found and fixed for next release.
