### ISSUE TITLE
tool tips sticking

### ISSUE THREAD

**Issue by DOMOCung** [Maetrim/DDOBuilderV2#2]
![image](https://github.com/Maetrim/DDOBuilderV2/assets/85769331/8ec3a173-ae1c-472c-bc39-2068633847ce)
If you quickly hover over an icon with a tooltip, sometimes the tooltip sticks even after you stop hovering over the icon.

**Comment by Maetrim** [comment]
I am aware of these issues and am in the process of fixing them.

**Comment by Maetrim** [comment]
These should be fixed
