### ISSUE TITLE
Enhancement Pane scrolling

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#20]
Not verified on .12 version, but on .11 version, the Enhancement pane scrollbar fails to allow scrolling down far enough to select the Universal Enhancement Tree buttons to enable/disable UETs.  In fact, even the pulldown menus to change the selected trees are below the lowest point to which the window will scroll.  It seems to consider the line below the Reset Tree button to be the bottom of the window.

In the image attached, note the scrollbar at the right is at its lowest position:

![image](https://github.com/Maetrim/DDOBuilderV2/assets/30603599/4edb1622-558e-4444-bab1-3e798451416d)

**Comment by Maetrim** [comment]
Fixed for next release.
