### ISSUE TITLE
Odd bug when selecting classes' levels; list loses ability to scroll down beyond L14

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#200]
In the Class and Levels pane,

I regularly click the first selector for the primary class, and allow all the levels to populate as that class.
Then I click the other two class selectors.
Then I run down the list and select at what level I wish to change the primary class to the secondary[ies].

When I start having to scroll down to make selections, it reverts to the top of the page after each selection, which is annoying, but not fatal.
However, when I'm making a selection around L15 or so (I'll try to narrow it down), sometimes after it refreshes the list and puts it back showing the top of the list, it loses the ability to scroll down beyond L14.  Looks like this:

![image](https://github.com/user-attachments/assets/373ffebd-46e5-4389-b437-22aebe449527)

I can fix it by clicking on a previous Life for the same file and then returning to the one in progress, but if it were a one-Life file?  Idk what would work.

**Comment by Maetrim** [comment]
This has been an intermittent issue I have been looking into. I may be able to fully reproduce it with these steps.

huzzah. i think I finally have a solution that works. Please give this some testing on the next build.
