### ISSUE TITLE
Shouldn't Stat & Skill Tomes be automatically populated when I add a New Life?

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#202]
This could be me.  Could be I'm not understanding the intent of the planner.

I'm setting up each TR as a New Life, all in one file for ongoing reference.  I'm using the Add Build option for if I intend to respec the toon during that life.

So when I create a New Life, it seems to me that it should be populated with all my previous Tome info.  I can understand why it can't pick my Past Life Feats automatically for me, but the Tome info doesn't change from one life to the next.. unless I make a purchase.

**Comment by DougSK** [comment]
Additional info:
It does not populate Stat or Skill Tomes.
It DOES, however, remember that I have a Racial AP tome and a Universal Tree AP Tome.

**Comment by Maetrim** [comment]
This is an issue that has also been reported on the Forums. I need to move all the Tomes into the "Character" from either the Build/Life levels of the data structures. Hopefully will have it on the next release.

**Comment by Maetrim** [comment]
Looks like I have a working solution for this. In the next release.
