### ISSUE TITLE
Switching Lives viewed leads to multiplication of AotS auto-granted Spells icons

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#203]
This one's a bit odd.  As mentioned in another Issue, I have combined all the Lives of my main into one build file.

The auto-granted Spells to which I refer are the ones from the Tainted Scholar tree (FF, Web, Crushing Despar, DW, etc).

When I was planning a new life and looking at a previous one for inspiration, I noticed, that the icons for these spells in the Acolyte of the Skin tab in the Spells and SLAs pane were duplicating.  Each time I switch away to look at another Life and back, they add additional copies.  Here's what it looks like after a few switches:

![image](https://github.com/user-attachments/assets/a45cdf6a-266b-4ae6-af05-0ed3595cb8b6)

**Comment by DougSK** [comment]
Note:  I only took the first four TS Cores. I assume the same would happen with GH & Energy Drain had I selected Core 5 and Core 6.

The duplication only seems to occur if I switch between two lives that have the same auto-granted spells.  If I switch from a Warlock life to another class life or from a Warlock life to another with different autogranted spells.. no problem.

It could well be something that happens with any autogranted spells from any class.  Will check further.

**Comment by DougSK** [comment]
Further testing shows that the same does NOT happen with the auto-granted Cure spells for Clerics nor the autogranted Repair and Inflict spells for Artificers.

It also doesn't happen with the Divine Emissary of Light/Darkness spells that get added to the spellbook without actually being autogranted.

I'm trying to remember another class that autogrants spells and thus far I'm coming up empty.

**Comment by Maetrim** [comment]
This is more than enough info to track it down. ty

**Comment by Maetrim** [comment]
Fixed for next release.
