### ISSUE TITLE
Dreadringers (gloves) - Profane spell focus effect is incorrect

### ISSUE THREAD

**Issue by onkei69** [Maetrim/DDOBuilderV2#204]
The Dreadringers gloves (ML 5) from Seasons of Feywild has an incorrect prefix.
Profane spell focus I is supposed to be +1 profane bonus to DC of all spells, not 25. The builder effectively adds 25 to all spell DCs instead of 1.

<img width="327" alt="{BE0E836E-45C1-4699-A169-BBDF131A7106}" src="https://github.com/user-attachments/assets/500988df-bb7e-4559-8015-091682da90ab" />

**Comment by Maetrim** [comment]
Item fixed for next release.
