### ISSUE TITLE
Error loading build for main made in .47 version into .48 version of DDOBuilder 2

### ISSUE THREAD

**Issue by DougSK** [Maetrim/DDOBuilderV2#205]
Log blew up with entries like this:

![image](https://github.com/user-attachments/assets/1c7eaa68-197b-4358-bd0c-61ad3ed11f5b)

If I select a previous life, it blows up again with the same info.

And in the process, it seems to have lost the Past Lives data:

![image](https://github.com/user-attachments/assets/f0a921c5-3a4d-40a1-b3e8-3eb03f0f88f9)

**Comment by DougSK** [comment]
This is what the past life info for the same file looks like in the .47 version:

![image](https://github.com/user-attachments/assets/b38eceb4-38e8-4e59-8aff-e495e49a637c)

**Comment by pevergreen** [comment]
No errors in log for me, but same past life panel issue, all greyed out. Happening on all my individual build files since upgrading

**Comment by pevergreen** [comment]
.48 has definitely bricked something though. Downgraded to 46 as I had it downloaded and when opening the file, all tomes and past lives have been stripped out.

**Comment by Maetrim** [comment]
Build 47 moved some data internally in the files, so its no longer backwards compatible.

Can you link the actual .47 build file so I can have something to test against here,

**Comment by Maetrim** [comment]
Did you main build have multiple Lives in it?

I think I may have a fairly simple solution (in code)

**Comment by Maetrim** [comment]
I have applied a fix that will allow older files to load correctly if they contain multiple lives.

**Comment by pevergreen** [comment]
No, I run one life per file, with multiple builds.

Lilwyn file has been edited in both 48 and then 46 i think
Corymr shadar kai is a brand new file done in 46, and untouched since, with only AP tomes added
pevergreen is a file untouched in 3+ months

All files impacted by this.
[v2.zip](https://github.com/user-attachments/files/18155631/v2.zip)

For fun, I imported a few v1 files into 48, and they come over with no past life information now.

**Comment by pevergreen** [comment]
Thanks - let me know if you want a v1 file, or any other single life files impacted

**Comment by Maetrim** [comment]
Looks like V1 import is working again. It also broke if you imported multiple V1 files in a row.
