### ISSUE TITLE
Vecna Unleashed items (and some other legendary) augment slots missing

### ISSUE THREAD

**Issue by rosstracy** [Maetrim/DDOBuilderV2#22]
None of the Legendary Vecna Unleashed boots have augment slots, just Mythic, Reaper and Deck:

Green, Blue, Yellow:
The Traveling Flow (Artifact)
The Shadow Flight (Artifact)
The Mocking Passage (Artifact)
The Kept Descent (Artifact)
The Furious Voyage (Artifact)
The Devouring Way (Artifact)

Green, Colorless
Legendary Steel-toed Steps
Legendary Skymage's Shoes
Legendary Lightning Railworker's Boots

These are from non-VU quests but are missing slots:

Osfield's Lightning Boots:  G, Y
Legendary Beachcombers:  G, C
Legendary Golden Greaves:  G, B
Legendary Firestorm Greaves:  Y, C

**Comment by rosstracy** [comment]
These VU Goggles have missing slots:

Green, Colorless:
Legendary Study Spectacles
Legendary Mystic Monocles
Legendary Eyes of Enlightenment


These other legendary Goggles are also missing slots:

Yellow:
Legendary Eyes of the Howling Hatred
Legendary Eyes of the Eternal Flame
Legendary Eyes of the Crushing Wave
Legendary Eyes of the Black Earth
Legendary Eternal Flameguard's Lenses
Legendary Blazing Sniper's Sights

Blue:
Legendary Black Earth Guardian's Lenses

**Comment by rosstracy** [comment]
These VU Necklaces have missing slots:

Green, Colorless:
Legendary War-rune Pendant
Legendary Song-Chime Locket
Legendary Blademark Amulet


These other Legendary necklaces are missing slots:

Legendary Pendant of the Sky:  G, C
Legendary Pendant of the Sea:  G, C
Legendary Pendant of Subtle Pain:  B

Legendary Vulkoorim Pendant:  B, Y
Legendary Hyena Claw Necklace:  Y, C
Legendary Hruvayah's Medallion:  B, G

**Comment by Maetrim** [comment]
I am currently fixing my list of bad items alphabetically. Currently working through the G's
