### ISSUE TITLE
Arch types don't count for completionist feat

### ISSUE THREAD

**Issue by YoureNotDead** [Maetrim/DDOBuilderV2#24]
When putting in Past lives skipping a base class and taking its Arch type, for example not having Bard but having Storm Singer, it will not count or reward Heroic Completionist feat.

**Comment by Maetrim** [comment]
hmm, this feat is meant to be setup automatically from all the declared classes. And does appear to be setup correctly, yet it doesn't get awarded from the Archetype past life feat. I'll get this fixed at some point this week.
![image](https://github.com/Maetrim/DDOBuilderV2/assets/30188223/c265e72d-8ca8-42d2-b05f-6e7fc47c39c6)

**Comment by Maetrim** [comment]
Seems like I renamed the Archetype past lives and didn't update the code that updates the Completionist feat with the requirements.
Fixed for next release.
