### ISSUE TITLE
Epic Spell Power: Sonic missing?

### ISSUE THREAD

**Issue by AKArachnae** [Maetrim/DDOBuilderV2#29]
I might be blind, so someone double-check me on this, but the ML 22 Epic Destiny Feat for Sonic Spell Power seems to be missing from the available options. Checked on multiple character files and with the epic feats only checked/unchecked (not that it should matter for destiny feats) and couldn't find it.

**Comment by Maetrim** [comment]
It is present in the file "Epic.class.xml" which is where it should be. However it is possible that you have accidentely added it to your list of Ignored Feats. You can reset these by deleting the FeatIgnoreList.xml file in your V2 installation foldder, or manually restore it by enabling the "Show Ignored Items" option in the toolbar and then right clicking the feat in the drop list to remove from the ignore list.
![image](https://github.com/Maetrim/DDOBuilderV2/assets/30188223/728181a4-62a4-4938-82cf-1e3ee889196b)

**Comment by Maetrim** [comment]
Closed.
