### ISSUE TITLE
some quick issues that I found

### ISSUE THREAD

**Issue by DOMOCung** [Maetrim/DDOBuilderV2#3]
Doublestrike epic feat is not appearing
(typo) Water elemental IMbue
Randomly flagged as unarmed (maybe a druid bug)(came up when I equipped a hands item)
Deleting a life cause it to crash (seems to depend on the build size . It would crash a fully built character) (It did not crash a build with only feats included)(crashed when I tried to open a new build over it)
Blightcaster thorn-kin/hive keeper forms are not given as stances
Blightcaster forms are not working at all
Adding then removing metamagics leaves a gap where the meta magics were
There are 2 sneak toggles
(something that would be neat is a stat of spell point percentage reduction)

Keep up the good work Maetrim :D
We all appreciate what you are doing for the community!

**Comment by Maetrim** [comment]
Various of these are fixed fro the next release. But leaving open as some still need to be actioned.

**Comment by Maetrim** [comment]
These should hopefully all be fixed in the last release.
