### ISSUE TITLE
Missing Warlock Pacts

### ISSUE THREAD

**Issue by rightwing66** [Maetrim/DDOBuilderV2#31]
In V2_2.0.0.23, Warlock pacts Fiend, The Great Old One and the Abyss appear to be missing.

**Comment by rightwing66** [comment]
Trolling through the xml files, it looks as though the feats are just missing from Warlock.class.xml.  I don't understand your structure well enough to add them.  If you have anything (document, forum discussion etc which would give me some kind of a start, I'll take a crack at adding them.)

**Comment by Maetrim** [comment]
I checked and the Pact feats are there in the Warlock.class.xml file. They will not show up in the UI unless you have the relevant Alignment set. If you do a search for "Warlock Pact" you will find the FeatSlot entry and any feat with a group of "Warlock Pact" can be trained in that feat slot type. You can see that the "Pact: Fiend" feat requires none of "any good alignment" to be listed.
