### ISSUE TITLE
Item Reaper typo

### ISSUE THREAD

**Issue by SpartanKiller13** [Maetrim/DDOBuilderV2#35]
Reaper Boot should probs be Reaper Boost, at least for non-boot items :)

Thanks!

**Comment by Maetrim** [comment]
This is actually deliberate as different reaper boosts go into different item type slots, so I need a way to determine the item type in the boost slot type and that is done in its name.

**Comment by SpartanKiller13** [comment]
Like helmets and cloaks etc having "Reaper Boot" slot is WAI, or you're still figuring out how to get the bonuses typed per slot?

**Comment by Maetrim** [comment]
I think they are WAI at the moment. Only boots should get a "Reaper Boot" option.
