### ISSUE TITLE
Sacred fist issues

### ISSUE THREAD

**Issue by zenith90210** [Maetrim/DDOBuilderV2#37]
1. holy sword is missing
2. divine grace is not giving the correct saves
3. sacred defender is not working for sacred fist (divine dream is not working?)

**Comment by Maetrim** [comment]
I just double checded all Sacred Fist spells, and only removed an erroneously present "Aid" spell at level 1. Looks like I had already fixed this issue in my local build as I made the effects of Holy Sword work.
