### ISSUE TITLE
Navigation icons do not match

### ISSUE THREAD

**Issue by JelloDDO** [Maetrim/DDOBuilderV2#4]
- When I click "Show/hide enhancements" it disables/enables skills tab
- When I click "Show/hide the skill plane" it disables/enables the builds tab
- When I click "Show feats" it disables/enables the stances tab
- When I click "Show/hide Builds plane" it disables/enables the breakdowns tab
- When I click "Show/hide special feats tab" it disables/enables the feats tab
- When I click "Show/hide breakdowns tab" it disables/enables the special feats/pastlives tab
- When I click "Show/hide stances tab" it disables/enables the enhancments tab

Currently the only ones that work as stated are: Reaper points, Epic Destinies, Gear/Equipment, Spells/SLAs, Granted Feats, and Automatic Feats

**Comment by Maetrim** [comment]
Fixed for next release also. Got messed up when I had to change the order of the docking pane creation order and this no longer matched the internal button ID order.
