### ISSUE TITLE
Spell Focus Augments 

### ISSUE THREAD

**Issue by SpartanKiller13** [Maetrim/DDOBuilderV2#42]
+2's (ML24) don't exist yet, just the +1's from ML16

Also currently giving -0 Enhancement bonus to DC's?

Thanks :)

**Comment by Maetrim** [comment]
I was told by Arcanaverse that the +2 versions of the augments were available in the DDO store or from epic gianthold. I took him at his word. I will leave them in for th emoment.

**Comment by SpartanKiller13** [comment]
Yeah they're in-game and stack fully (I think you typed them as augment bonus in V1), but at least in the version I have there's only +1's available and they don't stack with other enhancement bonuses. Sent from my  U.S.Cellular© Smartphone
-------- Original message --------From: Maetrim ***@***.***> Date: 6/21/24  4:40 AM  (GMT-06:00) To: Maetrim/DDOBuilderV2 ***@***.***> Cc: SpartanKiller13 ***@***.***>, Author ***@***.***> Subject: Re: [Maetrim/DDOBuilderV2] Spell Focus Augments  (Issue #42) 
I was told by Arcanaverse that the +2 versions of the augments were available in the DDO store or from epic gianthold. I took him at his word. I will leave them in for th emoment.

**Comment by Maetrim** [comment]
Closed as no follow up.
