### ISSUE TITLE
Spellpower stacking

### ISSUE THREAD

**Issue by SpartanKiller13** [Maetrim/DDOBuilderV2#43]
I've been wrong on this before, but I'm like 95% confident that Equipment Potency (like from Sacrarium Suncatcher) shouldn't be stacking with Equipment Spellpowers? I understand the crits and Artifact bonuses do, but that seems wild if Potency does as well. 

Or maybe that's why they're highlighted red? 

Also Implement Bonus doesn't appear to be showing up? 

Thanks and sorry for the spam lol

**Comment by Maetrim** [comment]
research on the wiki shows that Potency should only affect each individual spell power, not Universal. Fixed for next release.
