### ISSUE TITLE
A couple thoughts

### ISSUE THREAD

**Issue by Jokersir2** [Maetrim/DDOBuilderV2#49]
Loving the new builder.  And amazed on how quickly you are resolving issues we are posting.  It is awesome to have a character and all his past/future builds in one file where i can see the changes and compare.  I was checking out the quest/favor list and was curious if it would be possible to make our own custom list(s)?  I have 2 or 3 list of quest I run during reincarnates to vary my leveling route and break up the monotony.  Also, is there any future chance of putting all named items into your builder?  Even low level ones.  Would be sweet to put in my lvl 10 gear and be able to see the changes.  It would also help me remember what I normally wear at that level.  With that drop list option, would be nice to choose the right one and see all I am supposed to be wearing at specific milestones.  Anyway, thanks again and great job on the new builder!

**Comment by Maetrim** [comment]
Custom quest lists is something I could add in the future.

All named item are in the builder as of those that appear in the DDO Wiki. You can change the listed level ranges of items in the item select dialogs (it defaults to within 5 levels of your build"), but options of 10,15,20,..40 are available.

I am not sure you have noticed but if you single left click the build entry in the Builds pane you can set he level of your build in the life you're looking at. This allows you to gear your character and enhancements etc at a specific level, this is why Lives support multiple builds.

**Comment by Jokersir2** [comment]
Thank you, very helpful :)
