### ISSUE TITLE
Tier 5 abilities in Epic Destinies

### ISSUE THREAD

**Issue by JelloDDO** [Maetrim/DDOBuilderV2#5]
If you take a tier 5 ability but then remove it, the client will allow you to take other tier 5 abilities in other epic destiny trees, even if you have taken other abilities in that tree. 

Example: Taking "Weird" and "Shadow Mastery" out of shadow dancer will automatically lock out all other tier 5s, but if I just remove "Shadow Mastery" I will then be able to take any other tier 5s out of the other trees, even though "Weird" is still taken.

**Comment by Maetrim** [comment]
Fixed for next release.
