### ISSUE TITLE
Crafted Item issues

### ISSUE THREAD

**Issue by Jokersir2** [Maetrim/DDOBuilderV2#50]
-Insightful Search is not an option on a lvl 30 crafted item's extra slot.
-Level 30 crafted cloak "Insightful Spell Resistance"  should be +20 but showing +15
-Level 30 crafted ring - spell resistance is showing 30 but should be 39.
-Level 30 crafted ring - insightful proof against disease is not available in extra slot

Crafted item levels keep reverting back to lvl 1 or back to whatever their default min lvl is.  Example... Epic Gem of many facets keeps going back to lvl 20 even though I set it to 30.
It also appears that crafted items aren't changing skill stats.  I have disable +20 on that trinket and I changed the lvl from 30/20/15 and the entire time it stayed at 58 disable.

**Comment by Maetrim** [comment]
As a note, all my Cannith crafting values come from : https://ddowiki.com/page/Cannith_Crafting/table_3b

Ins Search added to the Cannith Necklace Extra slot
Spell Resistance values fixed
Ins Spell resistance values fixed 
Ins Proff Disease added to necklace/ring extra slots

Cannith crafted items will now correctly retain their level on load.

**Comment by Jokersir2** [comment]
Insightful Search should be available on Helm extra slot.  "Extra: Goggles, Helms, Necklaces, Trinkets, Rune Arms"
All the others look fixed.  As for the link to the table you sent, is that something I could correct when I see an issue and it would fix your ddobuilder automatically?  I never updated a wiki page though.  Not sure if I am allowed or the process to be allowed.  But if it is helpful, I can look into it.
