### ISSUE TITLE
AC breakdown - Shield AC incorrect

### ISSUE THREAD

**Issue by Ibtaken** [Maetrim/DDOBuilderV2#51]
AC from a shield is showing as "Enhancement" bonus in the AC breakdown, e.g. Leg Bulwark of Snow has a Shield Bonus of +30, but is showing as Enhancement Bonus of +15

"Shield X% Bonus" from Enhancements/Destinies are also missing from the AC breakdown, but I assume that's related to the missing "Shield Bonus"

**Comment by Maetrim** [comment]
The shield bonus field for all shields was parsed but never applied to the Item files. Added, and all Shield items updated.
