### ISSUE TITLE
issue with missing file when converting from the older version

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#54]
![image](https://github.com/Maetrim/DDOBuilderV2/assets/128959827/b0553e1a-596b-4085-868d-43bfb7738498)

**Comment by Mummykiller** [comment]
idk why but it crashes all the time

**Comment by Mummykiller** [comment]
i found the issue it was the racial feat from dragon born i had to swap to some other element and then swap back to fire 
you can close this ticket

**Comment by Maetrim** [comment]
I fixed an issue with the Dragonborn Racial feat being imported.
