### ISSUE TITLE
Slave Lords Items

### ISSUE THREAD

**Issue by SpartanKiller13** [Maetrim/DDOBuilderV2#55]
On V2.0.0.30, I still can't slot Slave Lords Shackles into boots, and if I just open the general equipment and get them they autoslot into bracers. 

Same for Five Rings & Chains

Also checked the heroic versions, in case only they got fixed, but those seem to have the same issue. 

Thanks!

**Comment by Maetrim** [comment]
Seems like everytime I re-parse the wiki files to create items, it messes up the multiple slots for these items. I have set them read only on my local to hopefully stop this from happening in the future
