### ISSUE TITLE
Missing Keeper of the Curse filigrees from Saltmarsh

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#59]
![image](https://github.com/Maetrim/DDOBuilderV2/assets/5016841/7583b0ab-0aad-4eed-92c9-2841275025ea)

I think we should see the Keeper of the Curse filigree set after Lunar Magic here, but it's not here (or in any of the other lists)

**Comment by Maetrim** [comment]
Its already been fixed, will be available in tomorrows update. I spelt "Filigree" as "Filligree" in its file (You can edit the file in the Filigree folder to fix your local version.
