### ISSUE TITLE
Class splits

### ISSUE THREAD

**Issue by JelloDDO** [Maetrim/DDOBuilderV2#6]
When attempting to make a 3-Class build, the builder crashes when I try to change the class. It crashes everytime without fail at the same place. Here are the conditions for which you can recreate this bug:

New Life ---> Shadar-Kai ---> Chaotic Neutral ---> All heroic, racial, iconic, epic past lives, as well as inherent bonuses and favor maxed ---> +8 Supreme tome ---> Level 1 Rogue (First class tab) ---> Level 2-4 Bard (Second Class tab)  ---> Level 5 Rogue ---> Level 6-7 Barbarian.

Upon trying to select level 6/7 as a barbarian, the entire builder crashes. I am on Windows 10 and am using the latest version of the V2 builder

**Comment by Maetrim** [comment]
Fixed for next release. Barbarian DR was missing the DR type field of "%"
