### ISSUE TITLE
Sapphire of Spell Agility adds to spell failure instead of reducing it

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#60]
![image](https://github.com/Maetrim/DDOBuilderV2/assets/5016841/cfe8480c-7581-4a15-8514-63f6afae9af3)

As you can see, the Sapphire of Spell Agility is applying a "bonus" of 15, which increases total arcane spell failure. It should instead subtract 15 from the total.

**Comment by Maetrim** [comment]
Fixed for next release.
