### ISSUE TITLE
Sapphire of Spell Agility's spell failure reduction should apply to shields

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#61]
I just tested this in game and the spell failure reduction from Sapphire of Spell Agility _does_ appear to work on shields in addition to armor. I don't see any text in game or on the wiki that supports it not working on shields.

Here is a screenshot taken from a build that has a Sapphire of Spell Agility equipped, and you can see that it doesn't register any effect on the Arcane Spell Failure (Shields) section.

![image](https://github.com/Maetrim/DDOBuilderV2/assets/5016841/a60bba5e-0b65-4348-bd5e-b5cda39b9631)

This screenshot is taken from the same build as the screenshot in issue https://github.com/Maetrim/DDOBuilderV2/issues/60, so the effect does apply (incorrectly) to armor.

**Comment by Maetrim** [comment]
This augment will jnow affect both totals.
