### ISSUE TITLE
Epic Past Lives not properly granting extra DP

### ISSUE THREAD

**Issue by Arakasu** [Maetrim/DDOBuilderV2#62]
For some reason, the builder does not give an extra DP at 3 or 6 EPLs. It appears to be properly giving a DP at 9 and every three EPLs after.

**Comment by Maetrim** [comment]
I did some investigation of these via the wiki and you should be getting:

1 fate point per 3 epic past lives (rounded down)
1 destiny point per 12 epic past lives (epic completionist)
1 destiny point per 3 fat points
4 destiny points per epic/legendary level

So I ran all my numbers against what he wiki says and it looks correct in the data of the builder. Can you provide an example .ddobuild file with the issue?

**Comment by Arakasu** [comment]
I figured out what the issue was after comparing both builder files and my actual character
