### ISSUE TITLE
Color Spray and Greater Color Spray are showing as Enchantment spell school

### ISSUE THREAD

**Issue by heartmanpd** [Maetrim/DDOBuilderV2#63]
The tool tip for Color Spray and Greater Color Spray is showing the spell school as Enchantment, when it should say Illusion.  I don't know if it impacts how the builder sets the spell DC for those spells (can't figure out how to see each spell's DC in this version),

**Comment by Maetrim** [comment]
I will change the spell school. Spell DCs are coming soon.
