### ISSUE TITLE
VKF T5

### ISSUE THREAD

**Issue by SpartanKiller13** [Maetrim/DDOBuilderV2#66]
I can't spend points in T5 Vistani? I reset, it's my only tree (see screenshot), I have no other T5's and >30 points spent in VKF. 

![Vistani](https://github.com/Maetrim/DDOBuilderV2/assets/116420018/0e3b0330-a61e-4629-b716-817fec2dd7c2)

Please advise,

Thanks

**Comment by Maetrim** [comment]
Is this an imported file? It looks like the internal log of which tree has a Tier5 trained in it has an old value in it. Can you see if any other tier 5's in any other trees are trainable?

Two options:

1. Edit the file directly and in the build in question delete the Trier5Tree entry
2. Find out which tree is tier 5 trainable, re-train a tier 5 and revoke it

**Comment by Maetrim** [comment]
No further info. Please report this issue as a new bug should it occur again.
