### ISSUE TITLE
deeper dive into the builder

### ISSUE THREAD

**Issue by DOMOCung** [Maetrim/DDOBuilderV2#7]
Past lives cannot be selected individually. You can circumvent this by activating all past lives and then deselecting them.
Fighter heavy armor / tactical bonus feats do not say the required level (but still do work)
Lvl 32 ability point does not apply.
You should get the bonus strength from Frenzied Berserker’s: Power rage while shifting (for razorclaw shifter).
I have an extra 3 fate points
Epic Prima/Martial passive Past lives do not get removed until you reopen the file.
Barbarian Damage Reduction does not get correctly shown in the breakdown (it does show the value when you click on it).
Legendary Dreadnaught: Unparallel Accuracy (LD Core 4) should not give 15 PRR.
Deific Warding gives you 2 more pr/mrr at 0 stacks (well it also doesn’t work).
Perfect Two Weapon Fighting is giving 5% Doublestrike.
Some archetypes are not getting the bonus epic caster/max caster levels. (Blight Caster, Dark Hunter, Acolyte of the Skin)
War Soul Divine Might has a red outline (functionally fine).
Shiradi Champion has the arcane background.
Archer’s Focus and Precision should not be mutually exclusive.
It would be convenient if pressing new build would automatically create a new life
Shiradi Champion: Feywild Attunement (T5) does not give the dodge per 4 wilderness feats
Arcane Archer: Elemental Arrow III (T4) only gives 1 imbue die instead of 2
Shiradi Champion: Pierce Deception is not giving the 5% doubleshot if you have Watchful Eye.
Precise Shot is giving a 5 Ranged power when it should not.
War Soul: Divine Will is scaling off of Charisma, and War Soul Divine Might is not working
Fate bonus to spell points is not working
I do not get spell points for 1 level of favored Soul. Also, I seem to be missing mana (compared to an exact copy of a build on both builders)
(This might fall under self buffs)You do not get the bonus spell penetration on your own bard song.
I will need to check this in-game but there is an inconsistency of the value of the scion spell crit damage between here and the wiki
Shiradi Champion: Fey Countenance (Core 4) does not give the bonus 2 to saving throws vs. Spells.
If you swap off of a weapon with impact/keen, it stays even when unequipped.
You do not get your dex to your Armor Class
Tiefling: Bloodhunt II (Core 3) is erroneously giving an imbue dice
Sorcerer fire elemental form is giving 2 caster levels instead of one
Wellspring of Power, Maximize, Empower, Intensify, Epic/Legendary Power should be in the Universal Spell Power section
Primal Avatar is not giving the full bonus (i.e. I am only getting 15 fire sp when I should have 20 (all 4 cores))
Draconic Incarnation (Draconic Bloodline: Red) is giving me 25 fire spell power instead of 20.
Tiefling: Incineration II is giving fire spell Crit Chance.
Wellspring of Power’s Spell Crit Damage should be in universal Spell Damage.

The new builder is shaping up to be great!
You are putting up some great work! :D

**Comment by DOMOCung** [comment]
Ok so I checked in game for my spell damage with both Scion of the Shadowfell and Epic Spell Power: Negative. I have 40% negative spell crit damage. The builderV2 is only giving me 30% negative spell crit damage.

**Comment by Maetrim** [comment]
All added to my known bug list.

**Comment by Maetrim** [comment]
I have fixes implemented for all but the spell point reduction at this time. Its still in my list of things to do. But closing this defect in the meantime.
