### ISSUE TITLE
Crafting issues

### ISSUE THREAD

**Issue by Jokersir2** [Maetrim/DDOBuilderV2#70]
-Vitality isn't showing up as a prefix on armor.  "Prefix: Armor"
-Disease Ward not showing up for bracers.  "Prefix: Bracers, Cloaks, Necklaces, Trinkets, Rune Arms"
-Insightful Search should be available on Helm extra slot. "Extra: Goggles, Helms, Necklaces, Trinkets, Rune Arms"
-Don't see Cannith Crafted as an option for weapons.  Only named weapons on the list.
-With a build capped at level 4, "Only show items within level" option will only show at most level 4.  Which makes sense but Gem of Many Facets can be any level.

**Comment by Maetrim** [comment]
Vitality, Disease Ward and Ins Search fixed.

Cannith Weapons are currently missing.

Not sure what I can do about the GomF allowing less than level 5
