### ISSUE TITLE
Crafting issues continued

### ISSUE THREAD

**Issue by Jokersir2** [Maetrim/DDOBuilderV2#71]
-Level 5 crafted item is showing 4% melee alacrity but should be 5%
-Insightful Spot should be available on Helm extra slot. "Extra: Goggles, Helms, Necklaces, Trinkets, Rune Arms"
-Insightful Vertigo should be available on Gloves.  "Extra: Gloves, Trinkets, Weapon"
-Insightful Search should be available on Goggles extra slot. "Extra: Goggles, Helms, Necklaces, Trinkets, Rune Arms"
-The level 16 augment "Topazes of Proof Against Poison +6" should be +6 and not +8
-Level 16 insightful insight is showing +10 but should be +31%

**Comment by Maetrim** [comment]
All the slot issues fixed. I will have to check the actual values at some point in the future as the wiki is out of date for most of them.
