### ISSUE TITLE
Master of X feats don't increase max caster level for the listed spells

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#72]
When taking a Master of X feat (e.g. Master of the Dead), spell tooltips don't show the increase to max caster level.

(Tested on Death Aura and Negative Energy Burst with Master of the Dead, and on Acid Blast with Master of Earth)

See example below

![image](https://github.com/Maetrim/DDOBuilderV2/assets/5016841/dd646984-9ad0-48ae-ad35-15281899abfc)

This is taken with the Master of the Dead feat, so Negative Energy Burst's max caster level should be at least 20 (I think it should actually be 26 in this case, because of being level 32 and having 6 stacks of Epic Knowledge, I'll make a separate issue to more easily track that bug)

**Comment by Maetrim** [comment]
This is a future update for individual spell MCL tracking

**Comment by Maetrim** [comment]
This is now implemented for the next version.
