### ISSUE TITLE
Spell tooltips' caster level/max caster level doesn't reflect Epic Knowledge stacks

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#73]
Epic Knowledge increases caster level and max caster level by +1 for every 2 levels past 20, so a total of +6 caster/max caster at level 32. Presumably this will increase to a maximum of +7 when Myth Drannor releases and the level cap increases to 34.

The tooltips for spells currently don't reflect this increase, as seen here: 
![image](https://github.com/Maetrim/DDOBuilderV2/assets/5016841/ad2eec1b-df8b-41d1-9440-3326967d852c)

Negative energy burst is shown with a max caster level of 10 instead of 16 (character is level 32)

**Comment by Maetrim** [comment]
This will be actioned at some point in the future.
