### ISSUE TITLE
Crashes when i add more 3 or more lives to a build 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#75]
i created a blank build with lives and reaper points spent copied it a 3 times and it crashed immediately

**Comment by Maetrim** [comment]
I have tried various scenarios to replicate this. Do you have a specific sequence that always causes it to happen?

**Comment by Mummykiller** [comment]
i just maxed out all the past lives and special feats tab copied it to clipboard and added it as a build couple of times it crashes quite often when i do that

**Comment by Mummykiller** [comment]
worked the first couple of times but now its not crashing

**Comment by Mummykiller** [comment]
umm found a reason for crashes 
multiselectors like exalted angel tier 3 send thingy a few times that i clicked on that it crashed my builder 
now i dont think its why i crushed multiple times when adding more then one life to a build but it is a cause 
for crashes

**Comment by Mummykiller** [comment]
it crashes alot idk what causes it tho 
and not only for me
