### ISSUE TITLE
spending reaper points doesn't let me take the top core

### ISSUE THREAD

**Issue by Kerkos** [Maetrim/DDOBuilderV2#78]
Spending reaper points on a build, I started to fill the Dire Thaumaturge tree.  I had all the points spent in the tree, but the builder does not let me get the 6th core.  It has a red message saying "Requires: No other "Capstone Enhancement" from another source.  The other two reaper trees do not appear to have this restriction.

**Comment by Maetrim** [comment]
Fixed for next release.
