### ISSUE TITLE
Unable to Select Pale Master: Spell Critical: Negative Energy II

### ISSUE THREAD

**Issue by nb756** [Maetrim/DDOBuilderV2#8]
Shows an error of "Unknown Enhancement:
![image](https://github.com/Maetrim/DDOBuilderV2/assets/60367116/9872053d-4cb6-49cf-a8b8-6b5eb8271865)

STR:
Create build as Deep Gnome.
Level 1 Wizard
Level 2 Rogue
Levels 3-19 Wizard
Level 20 Rogue
On Pale Master tree, select first core option
Select Pale Master: Spell Critical: Negative Energy I
Select Pale Master: Negative Energy Conduit x3
Attempt to select Pale Master: Spell Critical: Negative Energy II
See error.

ER:
Should be able to select Pale Master: Spell Critical: Negative Energy II when prerequisites are taken.

AR:
"Unknown Enhancement" error shows and unable to take enhancement.

**Comment by Maetrim** [comment]
Fixed for next release.
