### ISSUE TITLE
augment issues

### ISSUE THREAD

**Issue by Jokersir2** [Maetrim/DDOBuilderV2#81]
Missing Saphire of Spell Agility +10% - Min lvl 16
Topaz of Proof Against Disease +6 should be Min lvl 16 but yours says +8
Topaz of Proof Against Disease +8 should be Min lvl 20 but yours says +10
Topaz of Proof Against Poison +8 should be Min lvl 20 but yours says +10
Draconic Soul Gem should be min lvl 25 but you have 22

**Comment by Maetrim** [comment]
Spell Agility now has values for levels 12/16/20 of -5/-10/-15 as per the wiki (was previously only level 20 version)
The Topaz's were correct, but were affected by a different bug which is fixed in my local version where it applies the value for the next level up
Draconic Soul Gem level fixed.
