### ISSUE TITLE
Crashes when I mouse over the multi-selector in the EA epic destiny T3

### ISSUE THREAD

**Issue by neain** [Maetrim/DDOBuilderV2#82]
Tested it with my pure druid first life, and my full completionist. 

Mousing over the options crashes the builder in both.
The options are Flame Sphere, Cure Mod Mass, and light lightning bolt (did not test that the lightning bolt crashes my builder)

**Comment by Maetrim** [comment]
This issue was fixed in release 2.0.0.33, just dropped 2.0.0.34 that fixes an item equip bug. Please check the latest reelease.
