### ISSUE TITLE
kinetic charge bug

### ISSUE THREAD

**Issue by christhemisss** [Maetrim/DDOBuilderV2#88]
it does not give the +1 ac per 3 arti levels per stack, it is a flat +1

**Comment by Maetrim** [comment]
This is a very tricky one to implement as it is a cross between a slider and a class level being multiplied to together, and my current tech setup for this is not compatible with both being active at the same time. I will keep this one open until I can think of a valid solution.

**Comment by Maetrim** [comment]
Should now work for next release.
