### ISSUE TITLE
macrotech bugs

### ISSUE THREAD

**Issue by christhemisss** [Maetrim/DDOBuilderV2#90]
tinker tailoring adds +15 prr when it should not
sprockets does not add +10 prr when construct exemplar is taken

**Comment by christhemisss** [comment]
after looking, sprockets is giving the prr but it is not located in the same spot as the other machrotech buffs

**Comment by Maetrim** [comment]
Tinker Tailoring fixed. Minor issue in the Sprockets effects also fixed.
