### ISSUE TITLE
-10 to dc for some reason

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#92]
![image](https://github.com/user-attachments/assets/42fbe935-6d88-4eac-97ae-3fd271f517ec)

**Comment by Mummykiller** [comment]
also highten doesnt work on the spells even though it is active

**Comment by Maetrim** [comment]
Spell DC issue fixed for next release. Checking on the Heighten issue. Did it happen for a specific spell? The code checks to see if the Heighten metamagic is toggled on and the spell has the Heighten metamagic as an option for it.

**Comment by Maetrim** [comment]
![image](https://github.com/user-attachments/assets/c4d35a74-0cae-471f-85bb-ab7ccfd040ea)
As can be seen here, my FoD in this build is promoted 2 spell levels (to spell level 9 from 7)

**Comment by Mummykiller** [comment]
![image](https://github.com/user-attachments/assets/61f3b1d7-f4ee-477c-b9b2-7d26849b06ab)
![image](https://github.com/user-attachments/assets/7bb78a7b-c9fe-4366-808f-84f1e8e1636f)

**Comment by Mummykiller** [comment]
ah they dont have the highten effect them thats why

**Comment by Maetrim** [comment]
Doing a review of all spells set metamagics (oh joy)
