### ISSUE TITLE
Chained elementals and elder's knoalge should stack

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#93]
![image](https://github.com/user-attachments/assets/09d8c4da-6ae7-4291-8542-ac5d4bff5796)

**Comment by Maetrim** [comment]
Is the Elder's Knowledge bonus meant to be a Universal Spell Lore chance? The descriptions of both LEK and CE sets doesn't give that impression.

**Comment by Mummykiller** [comment]
it is i use it all the time on my casters

**Comment by Maetrim** [comment]
Spell lore changed from Spell Power to Universal Spell Lore in all 3 versions of the set bonus
