### ISSUE TITLE
failed to find image 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#94]
![image](https://github.com/user-attachments/assets/13609c59-3b91-4912-8f72-019f072b9369)
 every time i try to slot a quality stat in it it sends a failed to find image file

**Comment by Mummykiller** [comment]
![image](https://github.com/user-attachments/assets/20be0692-ef00-4244-acd8-c6edf414c532)
failed to find image

**Comment by Mummykiller** [comment]
![image](https://github.com/user-attachments/assets/28584781-a5ee-4082-83ca-da7de7c5fdc0)

**Comment by Maetrim** [comment]
This is expected behavior at the moment so I can track which things are missing images.
