### ISSUE TITLE
winter stance from druid not giving spellpower 

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#95]
![image](https://github.com/user-attachments/assets/5c149317-9a8f-44c5-b8eb-3bcddf5b21b3)
![image](https://github.com/user-attachments/assets/ca53c4ee-1ee2-4621-b404-53c909fe97ec)
summer works fine it looks like 
winter  gives to lighning and acid but not to cold

**Comment by Maetrim** [comment]
Fixed for Cold spell power,
