### ISSUE TITLE
Favor errors

### ISSUE THREAD

**Issue by Guntharm** [Maetrim/DDOBuilderV2#96]
Here are a list of the favor errors i've found so far:

Missing Quests/Raids:
Precious Cargo  level 25 The Free Agents base 7 
The Fall of Truth level 25 Agents of Agronnessen base 8
Total Chaos level 22 The Gatekeepers base 3

Wrong base amounts:
The Bounty Hunter should be 5 not 4 base
Under the Cover of Darkness should be 2 not 3
The Lost Thread should be base 8 not 7

Quest Catastrophe should be Agents of Argonnessen favor not The Coin Lords

Quest Stealer of Souls should have a casual option.

Great work on V2
Guntharm

**Comment by Guntharm** [comment]
Wondering if there is a way to make it easier to do then one at a time.

**Comment by Maetrim** [comment]
All fixed for next release. Missing ones also added.
