### ISSUE TITLE
Missing dino bone augments

### ISSUE THREAD

**Issue by Mummykiller** [Maetrim/DDOBuilderV2#98]
![image](https://github.com/user-attachments/assets/612f0885-a1ec-4765-9e11-957f2c78343b)

**Comment by Maetrim** [comment]
Was this an ungrade from an old file? Creating a set with a new "Dinosaue Bone Cloak" does not have any kind of augment issue.

**Comment by Mummykiller** [comment]
possible

**Comment by Maetrim** [comment]
Closed as no additional info. Please open a new issue if this occurs again.
