### ISSUE TITLE
Wellspring (Season's Herald) not granting its bonus to Shillelagh

### ISSUE THREAD

**Issue by tevwoods** [Maetrim/DDOBuilderV2#99]
Wellspring includes this text: 

The effects of your [Shillelagh](https://ddowiki.com/page/Shillelagh) spell are doubled.

Shillelagh effect on "Base Damage" (on a quarterstaff):
![image](https://github.com/user-attachments/assets/5b72dee2-9533-40bc-968f-cd7579e1f5d2)

While Wellspring is taken: 
![image](https://github.com/user-attachments/assets/5cbb8d4a-9456-4c69-a623-1f8556b39064)

Because the character is wielding a quarterstaff, shillelagh buff is active, and the wellspring enhancement is taken, Shillelagh's bonus should be 2[W] instead of 1

I also confirmed that a Club type weapon receives only 0.5[W] instead of 1[W] in this case

**Comment by Maetrim** [comment]
Fixed for next release.
